apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-conversion
  namespace: github-lab
  labels:
    app: video-conversion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-conversion
  template:
    metadata:
      labels:
        app: video-conversion
    spec:
      containers:
      - name: video-conversion
        image: 767397705569.dkr.ecr.us-east-1.amazonaws.com/video-conversion:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: video-conversion
  namespace: github-lab
spec:
  selector:
    app: video-conversion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: video-conversion
  namespace: github-lab
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: video.kapil-lab.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: video-conversion
            port:
              number: 80
